subchart:
  enabled: false
  replicaCount: 1
  
mongodb:
  enabled: false
  service:
    type: LoadBalancer
    port: 27017

wordpress:
  enabled: false

grafana:
  enabled: false
  service:
    type: LoadBalancer
    port: 3000

elasticsearch:
  enabled: false
  service:
    type: LoadBalancer
    port: 9200

joomla:
  enabled: true
  service:
    type: LoadBalancer
    port: 8080